[package]
name = "truco_domain_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
truco_domain_engine = { git = "https://github.com/Mirkopoj/truco_state_pattern.git" }
